version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: geneaia-db-local
    environment:
      POSTGRES_DB: geneaia_local
      POSTGRES_USER: geneaia_user
      POSTGRES_PASSWORD: geneaia_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geneaia_user -d geneaia_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: geneaia-backend-local
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://geneaia_user:geneaia_password@postgres:5432/geneaia_local?schema=public
      - JWT_SECRET=dev-secret-key-for-local-development-only
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: geneaia-frontend-local
    environment:
      - VITE_API_URL=http://localhost:3001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  default:
    name: geneaia-local
