version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: geneaia-db-staging
    environment:
      POSTGRES_DB: geneaia_staging
      POSTGRES_USER: geneaia_staging
      POSTGRES_PASSWORD: staging123password
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geneaia_staging -d geneaia_staging"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/geneaia-backend:staging
    container_name: geneaia-backend-staging
    environment:
      - NODE_ENV=staging
      - DATABASE_URL=postgresql://geneaia_staging:staging123password@postgres:5432/geneaia_staging?schema=public
      - JWT_SECRET=staging_jwt_secret_xyz789abc
      - CORS_ORIGIN=http://168.231.86.179:3000
      - PORT=3001
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/geneaia-frontend:staging
    container_name: geneaia-frontend-staging
    environment:
      - VITE_API_URL=http://168.231.86.179:3001/api
    restart: unless-stopped
    ports:
      - "3000:80"

volumes:
  postgres_staging_data:
    driver: local

networks:
  default:
    name: geneaia-staging
